##R PROGRAMMING WEEK 3 BY CHINMAY MALVANKAR

##231O2C0073

##CMPNC

In [1]:
c(2,3,5,7) + c(-2,-3,-5,8)

[1]  0  0  0 15

In [2]:
2^3
2**3
2^0.5
2**0.5
2^-0.5

[1] 8

[1] 8

[1] 1.414214

[1] 1.414214

[1] 0.7071068

In [3]:
c(2,3,5,7)^2

[1]  4  9 25 49

In [4]:
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

In [5]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

In [6]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

In [7]:
2 %/% 2
5 %/% 2
7 %/% 3

[1] 1

[1] 2

[1] 2

In [8]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

In [9]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

In [10]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

In [11]:
2 %% 2
3 %% 2
7 %% 3
7 %% 4

[1] 0

[1] 1

[1] 1

[1] 3

In [12]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

In [13]:
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1

In [14]:
c(2,3,5) %% c(2,3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

In [15]:
max(1.2, 3.4, -7.8)
max(c(1.2, 3.4, -7.8))

[1] 3.4

[1] 3.4

In [16]:
min(1.2, 3.4, -7.8)
min(c(1.2, 3.4, -7.8))

[1] -7.8

[1] -7.8

In [17]:
mean(2, 3, 4)
mean(c(2, 3, 4))

[1] 2

[1] 3

In [18]:
abs(-4)
abs(c(-1,-2,-3,4,5))

[1] 4

[1] 1 2 3 4 5

In [19]:
sqrt(4)
sqrt(c(4,9,16,25))

[1] 2

[1] 2 3 4 5

In [20]:
sum(c(2,3,5,7))
prod(c(2,3,5,7))

[1] 17

[1] 210

In [21]:
round(1.23)
round(1.83)

[1] 1

[1] 2

In [22]:
log(10)
log(exp(1))
log(c(10,100,1000))

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

In [23]:
log10(10)
log10(100)
log10(c(10,100,1000))

[1] 1

[1] 2

[1] 1 2 3

In [24]:
x1 = c(1,2,3,4)
x1
x2 = x1^2
x2

[1] 1 2 3 4

[1]  1  4  9 16

In [25]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))
abs(c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)))

[1] 21 22 23 24

[1] 19 18 17 16

In [26]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [27]:
x[3,2]

[1] 7

In [28]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow=FALSE)
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [29]:
y = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow=TRUE)
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [30]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x
dim(x)
nrow(x)
ncol(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 4 2

[1] 4

[1] 2

In [31]:
mode(x)
attributes(x)

[1] "numeric"

$dim
[1] 4 2

In [32]:
help("matrix")

In [33]:
is.matrix(as.matrix(1:10))
data(warpbreaks)
!is.matrix(warpbreaks)
warpbreaks[1:10,]
as.matrix(warpbreaks[1:10,])

[1] TRUE

[1] TRUE

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M