R PROGRAMMING WEEK 4

CHINMAY MALVANKAR

23102C0073

CMPN C

### Renaming the row and column names

In [1]:
x = matrix( nrow=4, ncol=3, data=c(1:12) )
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [2]:
rownames(x) = c("r1", "r2", "r3", "r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [3]:
colnames(x) = c("c1", "c2", "c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

### Assigning a specified number to all matrix elements

In [4]:
x = matrix( nrow=4, ncol=2, data=2 )
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

### Matrix Operations: Diagonal matrix

In [5]:
d = diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [6]:
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

### Matrix Operations: Transpose

In [7]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T )
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [8]:
xt = t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

### Matrix Operations: Row and column sums

In [9]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [10]:
rowSums(x)

[1]  6  8 10 12

In [11]:
colSums(x)

[1] 10 26

### Matrix Operations: Row and column means

In [12]:
rowMeans(x)

[1] 3 4 5 6

In [13]:
colMeans(x)

[1] 2.5 6.5

### Access to rows, columns or submatrices

In [14]:
x = matrix( nrow=5, ncol=3, byrow=T, data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [15]:
x[3,]

[1] 7 8 9

In [16]:
x[,2]

[1]  2  5  8 11 14

In [17]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [18]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

### Addition of a matrix with a constant

In [19]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [20]:
x+5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

### Subtraction of a matrix with a constant

In [21]:
x - 5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

### Multiplication of a matrix with a constant

In [22]:
5*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

### Division of a matrix with a constant

In [23]:
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

### Addition and subtraction of matrices (of same dimensions)

In [24]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)
x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [25]:
x + y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

In [26]:
x - y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

### Multiplication of a matrix with a constant (example)

In [27]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [28]:
4*x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

### Addition and subtraction using multiplication example

In [29]:
x + 4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [30]:
4*x - x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

### Multiplication of matrices

In [31]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)
x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

In [32]:
x%*%y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [33]:
y%*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

### Another example: Consider the multiplication of X' and X

In [34]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [35]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [36]:
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

### Cross Product of a matrix X, X'X, with crossprod()

In [37]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

### Concatenating matrices

In [38]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

In [39]:
rbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

In [40]:
cbind(x, y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

### Inverse of matrix — solve()

In [41]:
y = matrix( nrow = 2, ncol = 2, byrow = T, data = c(84,100,100,120))
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [42]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

### Eigen values and eigen vectors of matrix — eigen()

In [43]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

### Examples: Use of | and ||

In [44]:
x=8
(x < 10) || (x < 2)

[1] TRUE

In [45]:
x=18
(x < 10) || (x < 2)

[1] FALSE

In [47]:
x = c(8,18)
(x < 10) || (x < 2)

ERROR: Error in (x < 10) || (x < 2): 'length = 2' in coercion to 'logical(1)'

In [ ]:
(x < 10) | (x < 2)

### Examples: Use of & and &&

In [ ]:
x = 5
(x < 10) && (x > 2)

In [ ]:
x = 15
(x < 10) && (x > 2)

In [ ]:
x = c(8,18)
(x < 10) && (x > 2)

In [ ]:
(x < 10) & (x > 2)

### Examples

In [ ]:
x = 1:6 # Generates x=1,2,3,4,5,6
x

In [ ]:
(x > 2) & (x < 5) # Checks whether the values are greater than 2 and less than 5

In [ ]:
x[(x > 2) & (x < 5)] # Finds which values are greater than 2 and smaller than 5

In [ ]:
(x > 2) | (x < 5) # Checks whether the values are greater than 2 or less than 5

In [ ]:
x[(x > 2) | (x < 5)] # Finds which values are greater than 2 or smaller than 5

### Example of "The longer form evaluates left to right examining only the first element of each vector"

In [ ]:
x = 1:6      # Generates x = 1,2,3,4,5,6
(x > 2) && (x < 5)

In [ ]:
# is equivalent to:
(x[1] > 2) & (x[1] < 5)

### Example of Standard logical operations

In [ ]:
x = TRUE
y = FALSE
x & y     # x AND y

In [ ]:
x | y     # x OR y

In [ ]:
!x        # negation of x

### Example

In [ ]:
x = 5
Logical1 = (x > 2)
Logical1

In [ ]:
is.logical(Logical1)

In [ ]:
Logical2 = (x < 10)
Logical2

In [ ]:
is.logical(Logical2)

In [ ]:
Logical3 = (x != 5)
Logical3

In [ ]:
is.logical(Logical3)

### Example (continued)

In [ ]:
x = 5
Logical4 = (2*x > 11)
Logical4

In [ ]:
is.logical(Logical4)

In [ ]:
Logical5 = (3*x <20)
Logical5

In [ ]:
is.logical(Logical5)

### Examples: relational operators

In [ ]:
8 > 7

In [ ]:
7 < 5

In [ ]:
7 > 7

In [ ]:
7 >= 7

In [ ]:
8 < 8

In [ ]:
8 <= 8

In [ ]:
8 != 9

In [ ]:
9 != 9

In [ ]:
7 == 7

In [ ]:
7 == 8

In [ ]:
x = TRUE
!x

### Examples: vectorized comparisons

In [ ]:
x = c(1, 2, 3)
y = c(4, 5, 6)

In [ ]:
x > y     # Compares 1 > 4, 2 > 5, 3 > 6

In [ ]:
x < y     # Compares 1 < 4, 2 < 5, 3 < 6

In [ ]:
x != y    # Compares 1 != 4, 2 != 5, 3 != 6

In [ ]:
x == y    # Compares 1 == 4, 2 == 5, 3 == 6

### Examples: isTRUE / isFALSE

In [ ]:
isTRUE(8 < 6)   # Is 8 less than 6?

In [ ]:
isTRUE(8 > 6)   # Is 8 greater than 6?

In [ ]:
isFALSE(5 < 8)  # Is 5 less than 8?

In [ ]:
isFALSE(5 > 8)  # Is 5 greater than 8?